name: SimpleSeq
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - bioconductor-apeglm=1.24.0
 - bioconductor-biocparallel=1.36.0
 - bioconductor-clusterprofiler=4.10.0
 - bioconductor-deseq2=1.42.0
 - bioconductor-diffbind=3.12.0
 - bioconductor-enhancedvolcano=1.20.0
 - bioconductor-genomicranges=1.54.1
 - bioconductor-org.hs.eg.db=3.18.0
 - bioconductor-reactomepa=1.46.0
 - bioconductor-topgo=2.54.0
 - biopython=1.84
 - bowtie2=2.5.4
 - cutadapt=4.9
 - fastqc=0.12.1
 - hisat2=2.2.1
 - htseq=2.0.5
 - macs2=2.2.9.1
 - picard=3.2.0
 - python=3.10.4
 - r-argparse=2.2.2
 - r-base=4.3.1
 - r-dplyr=1.1.4
 - r-ggplot2=3.5.1
 - r-ggpubr=0.6.0
 - r-openxlsx=4.2.7
 - r-pheatmap=1.0.12
 - r-rcolorbrewer=1.1_3
 - r-readr=2.1.5
 - r-rlang=1.1.4
 - r-tidyverse=2.0.0
 - samtools=1.20
 - seaborn=0.13.2
